jenkins:
  authorizationStrategy: unsecured
jobs:
  - script: >
      pipelineJob('lineage') {
        definition {
          cpsScm {
            scriptPath 'Jenkinsfile'
            scm {
              git {
                remote {
                  url 'https://github.com/dtrunk90/jenkins-lineage-docker.git'
                }
                extensions {}
              }
            }
          }
        }
      }
security:
  scriptApproval:
    approvedSignatures:
      - method groovy.util.slurpersupport.GPathResult appendNode java.lang.Object
unclassified:
  gitSCM:
    globalConfigEmail: "john.doe@example.com"
    globalConfigName: "John Doe"
