jenkins:
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  numExecutors: 1
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin
  slaveAgentPort: disable
jobs:
  - script: >
      pipelineJob('lineage') {
        definition {
          cpsScm {
            scriptPath 'Jenkinsfile'
            scm {
              git {
                configure { git ->
                  git / 'extensions' / 'hudson.plugins.git.extensions.impl.SparseCheckoutPaths' / 'sparseCheckoutPaths' {
                    'hudson.plugins.git.extensions.impl.SparseCheckoutPath' {
                      path('Jenkinsfile')
                    }
                  }
                }
                extensions {}
                remote {
                  url 'https://github.com/dtrunk90/jenkins-lineage-docker.git'
                }
              }
            }
          }
        }
      }
security:
  scriptApproval:
    approvedSignatures:
      - method groovy.lang.GroovyObject getProperty java.lang.String
      - method groovy.util.XmlSlurper parseText java.lang.String
      - method groovy.util.slurpersupport.GPathResult appendNode java.lang.Object
      - method groovy.util.slurpersupport.GPathResult leftShift java.lang.Object
      - new groovy.util.XmlSlurper
      - staticMethod groovy.xml.XmlUtil serialize groovy.util.slurpersupport.GPathResult
      - staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods getAt java.lang.Object java.lang.String
unclassified:
  gitSCM:
    globalConfigEmail: "john.doe@example.com"
    globalConfigName: "John Doe"
  location:
    url: http://localhost
